{{- if .Values.flexprice.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "flexprice.serviceAccountName" . }}
  labels:
    {{- include "flexprice.labels" . | nindent 4 }}
  {{- with .Values.flexprice.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
